version: '3.1'

services:
  server:
    image: wow-server
    build: 
      context: ../../src/Geo
      dockerfile: ../../Dockerfile.server
    container_name: wow-server
    ports:
      - "8888:8888"
    volumes:
      - ./server.yaml:/config.yaml

  client:
    image: wow-client
    build: 
      context: ../..
      dockerfile: ../../Dockerfile.client
    container_name: wow-client
    volumes:
      - ./client.yaml:/config.yaml